name: Publish

on:
  workflow_dispatch:
    inputs:
      isSnapshot:
        required: true
        type: boolean
  workflow_call:
    inputs:
      isSnapshot:
        required: true
        type: boolean

jobs:
  nexus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: temurin@17.0.5=tgz+https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5%2B8/OpenJDK17U-jdk_x64_linux_hotspot_17.0.5_8.tar.gz
      - name: set tag
        if: ${{ inputs.isSnapshot == false }}
        run: GITHUB_REF="refs/tags/$(git tag --points-at HEAD)"
      - name: run ci-release
        run: |
          echo $GITHUB_REF
          sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.GPG_KEY }}
          SONATYPE_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.NEXUS_USER }}
